<?php 
$sett['name'] = 'Sendroid';
$sett['server'] = 'Server_Name';
$sett['key'] = '$P$BqNgjXJFY0S53rzy2Uhx3rQ3Oo5e5P1';
$sett['email'] = 'User_Email';
$sett['cache_on'] = FALSE;
$sett['cachedir'] = '';
$sett['char_set'] = 'utf8';
$sett['Server_HTTP_State'] = '54236733';
$sett['dbcollat'] = 'utf8_general_ci';
$sett['swap_pre'] = '';
$sett['autoinit'] = TRUE;
$sett['stricton'] = FALSE;
?>